name: build-and-deploy
on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Clone Source Code
        uses: actions/checkout@v4

      - name: Build Image
        run: docker build -t 192.0.2.40:5000/prct-site:latest .
        
      - name: Push Image
        run: docker push 192.0.2.40:5000/prct-site:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Pull New Image
        run: |
          ssh deployuser@192.0.2.20 "
            docker pull 192.0.2.40:5000/prct-site:latest
          "

      - name: Remove Old Image
        run: |
          ssh deployuser@192.0.2.20 "
            docker stop prct-site || true &&
            docker rm prct-site || true
          "

      - name: Run New Image
        run: |
          ssh deployuser@192.0.2.20 "
            docker run -d \
            --name prct-site \
            --restart unless-stopped \
            -p 8080:5000 \
            -v /opt/prct-site/wpad_.dat:/app/wpad_.dat \
            -v /opt/prct-site/config.json:/app/config.json \            
            192.0.2.40:5000/prct-site:latest
          "