name: build-and-push
on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Clone
        uses: git clone http://192.0.2.41:3000/deployuser/app .

      - name: Build Image
        run: docker build -t 192.0.2.40:5000/prct-site:latest .
        
      - name: Push Image
        run: docker push 192.0.2.40:5000/prct-site:latest .