name: update-config
on:
  push:
    paths:
      - 'volume/**'

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Pull Files
        runs: |
          ssh deployuser@192.0.2.20 "
            wget -O /opt/prct-site/config.json http://192.0.2.41:3000/deployuser/app/raw/branch/master/volume/config.json &&
            wget -O /opt/prct-site/wpad_.dat http://192.0.2.41:3000/deployuser/app/raw/branch/master/volume/wpad_.dat
          "